import { Geist, Geist_Mono } from "next/font/google";
import { Inter } from 'next/font/google';
import "./globals.css";
import Navigation from "./components/Navigation"
import Footer from "./components/Footer";
import NavBar from "./components/NavBar";
import { ReactLenis } from 'lenis/react'
const inter = Inter({ 
  variable: "--font-inter-sans",
  subsets: ['latin'] });

  const lenisOptions = {
    lerp: 0.1,
    duration: 1.5,
    smoothTouch: false, //smooth scroll for touch devices
    smooth: true,
  };

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <ReactLenis root options={lenisOptions}>
      <body
        className={`${inter.variable}  antialiased bg-gray-100`}
      >
        <main  className="wrapper ">
         
          {/* <NavBar /> */}

      
        
          {children}
          <Footer/>
        </main>
        
      </body>
      </ReactLenis>
    </html>
  );
}
